import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:frontend_otis/domain/usecases/payment/process_payment_usecase.dart';
import 'payment_event.dart';
import 'payment_state.dart';

import 'package:frontend_otis/core/enums/order_enums.dart';
import 'package:frontend_otis/domain/entities/payment.dart';
import 'package:frontend_otis/domain/usecases/payment/create_payment_usecase.dart';

class PaymentBloc extends Bloc<PaymentEvent, PaymentState> {
  final ProcessPaymentUseCase processPayment;
  final CreatePaymentUseCase createPayment;

  PaymentBloc({required this.processPayment, required this.createPayment})
    : super(PaymentInitial()) {
    on<SelectPaymentMethodEvent>((event, emit) async {
      emit(PaymentLoading());
      try {
        final payment = Payment(
          id: '', // Generated by repo/DB
          orderId: event.orderId,
          paymentCode:
              'GEN-${DateTime.now().millisecondsSinceEpoch}', // Temp code
          amount: event.amount,
          method: event.method,
          status: PaymentStatus.pending,
          createdAt: DateTime.now(),
        );

        final result = await createPayment(payment);

        result.fold(
          (failure) => emit(PaymentFailure(failure.message)),
          // If COD, we treat "Initiated" as effectively done UI-wise (Processing).
          // If Bank, we show QR.
          // PaymentInitiated state handles both, UI decides what to show.
          (createdPayment) => emit(PaymentInitiated(createdPayment)),
        );
      } catch (e) {
        emit(PaymentFailure(e.toString()));
      }
    });

    on<ProcessPaymentEvent>((event, emit) async {
      // ... existing logic ...
      emit(PaymentLoading());

      try {
        final result = await processPayment(event.orderId);

        result.fold((failure) => emit(PaymentFailure(failure.message)), (
          payment,
        ) {
          if (payment.status == PaymentStatus.success) {
            emit(PaymentSuccess());
          } else {
            emit(
              PaymentFailure("Payment status: ${payment.status.displayName}"),
            );
          }
        });
      } catch (e) {
        emit(PaymentFailure(e.toString()));
      }
    });
  }
}
